---
title: "03_modeling_clinicalevent"
# output: html_document
---

# Environment

```{r}
library(skimr)
library(mgcv)
library(parallel)
library(parglm)
library(pROC)
library(ggplot2)
library(tibble)
library(dplyr)
library(feather)
library(broom)
library(htmlTable)
library(caret)
library(kableExtra)
# library(webshot2)

extract_coef_pval_OR <- function(model) {
  
  as.data.frame(tibble(term = names(model$coefficients),
                       estimate = model$coefficients,
                       std.error = sqrt(diag(vcov(model))),
                       statistic = model$coefficients / sqrt(diag(vcov(model))),
                       p.value = 2 * (1 - pnorm(abs(statistic))),
                       OR = round(exp(estimate),2),
                       OR_CI_lower = round(exp(estimate - 1.96 * std.error),2),
                       OR_CI_upper = round(exp(estimate + 1.96 * std.error),2)
  )
  )
} 
```

# Load File

```{r}
final_dataset <- (
  readRDS(
    "~/projects/vacunas_brands_2025/Rfiles/final_dataset_brands.rds"
  )
)
```

# Analysis of variable vac_1shot

## Logistic Regression of Clinical Event

### Fitting the model

```{r}
print('Logistic Regression of Clinical Event')
print(Sys.time())
logreg_hadm <- gam(
   clinical_event ~ s(age) + desc_sexo + variant_period + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc +  hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + ultima_inmun_infecc_bin + vac_1shot,
  data =  final_dataset,
  family=binomial(), 
  method = "REML")
print(Sys.time())
```

### Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_hadm_1 <- extract_coef_pval_OR(logreg_hadm)

```

### Forest Plot

```{r}
variable_order <- rev(c(
  "Intercept", "AstraZeneca", "Janssen", "Moderna", "Pfizer/BioNTech",
  "No vaccination/infection", "Last vaccination/infection (>31-60 days ago)", "Last vaccination/infection (>61-90 days ago)", "Last vaccination/infection (>91-120 days ago)", "Last vaccination/infection (>121-180 days ago)", "Last vaccination/infection (>180 days ago)"))

coef_pval_df_hadm_2 <- coef_pval_df_hadm_1  %>%
  mutate(
    term = case_when(
      term == "(Intercept)" ~ "Intercept",
      term == "age" ~ "Age",
      term == "desc_sexoHombre" ~ "Sex (male)",
      term == "variant_periodα" ~ "Period of α predominance",
      term == "variant_periodα/Δ transition" ~ "α-Δ transition period",
      term == "variant_periodΔ" ~ "Period of Δ predominance",
      term == "variant_periodΔ/Ό transition" ~ "Δ-Ό transition period",
      term == "variant_periodΌ" ~ "Period of Ό predominance",
      term == "n_prev_infeccUno" ~ "Number of Previous Infections (1)",
      term == "n_prev_infeccDos" ~ "Number of Previous Infections (2)",
      term == "asmaSí" ~ "Asthma",
      term == "cardiopatia_isquemicaSí" ~ "Ischemic heart disease",
      term == "cirrosis_hepaticaSí" ~ "Hepatic cirrhosis",
      term == "diabetesSí" ~ "Diabetes",
      term == "epocSí" ~ "Chronic Obstructive Pulmonary Disease (COPD)",
      term == "hepatopatia_cronica_excepto_cirrosisSí" ~ "Chronic Hepatic Disease (except cirrhosis)",
      term == "hipertensionSí" ~ "Hypertension",
      term == "insuficiencia_cardiacaSí" ~ "Heart failure",
      term == "insuficiencia_renal_cronicaSí" ~ "Chronic kidney disease",
      term == "vihSí" ~ "HIV+",
      term == "cancer_hematologicoSí" ~ "Haematologic cancer",
      term == "cancer_organo_solidoSí" ~ "Solid organ cancer",
      term == "ultima_inmun_infecc_binNone" ~ "No vaccination/infection",
      term == "ultima_inmun_infecc_bin31-60" ~ "Last vaccination/infection (>31-60 days ago)",
      term == "ultima_inmun_infecc_bin31-60" ~ "Last vaccination/infection (>31-60 days ago)",
      term == "ultima_inmun_infecc_bin61-90" ~ "Last vaccination/infection (>61-90 days ago)",
      term == "ultima_inmun_infecc_bin91-120" ~ "Last vaccination/infection (>91-120 days ago)",
      term == "ultima_inmun_infecc_bin121-180" ~ "Last vaccination/infection (>121-180 days ago)",
      term == "ultima_inmun_infecc_bin>180" ~ "Last vaccination/infection (>180 days ago)",
      term == "vac_1shotAstraZeneca" ~ "AstraZeneca",
      term == "vac_1shotJanssen" ~ "Janssen",
      term == "vac_1shotModerna" ~ "Moderna",
      term == "vac_1shotPfizer/BioNTech" ~ "Pfizer/BioNTech",
      term == "vac_1shotOther" ~ "Other",
      TRUE ~ term
    ),
    term = factor(term, levels = variable_order), 
    adverse_protective = case_when(
           OR_CI_lower > 1 & OR_CI_upper > 1 ~ "Adverse",
           OR_CI_lower < 1 & OR_CI_upper < 1 ~ "Protective",
           TRUE ~ "Inconclusive"
    ),
    adverse_protective = factor(adverse_protective, levels = c("Adverse", "Protective", "Inconclusive"))) %>%
  filter(term != "Intercept")

# Save OR table and print in console
write.csv(coef_pval_df_hadm_2,'~/projects/vacunas_brands_2025/data/oddsratio_vac_1shot_clinicalevent.csv')
htmlTable(coef_pval_df_hadm_2[,c("term","OR","OR_CI_lower","OR_CI_upper")], caption = "1-shot Regimen - Odds Ratio and Confidence Intervals for composite outcome-associated Factors")

# # Export OR table as kable 
# or_table <- coef_pval_df_hadm_2 %>%
#   select(term, OR, OR_CI_lower, OR_CI_upper) %>%
#   mutate(
#     term = factor(term, levels = variable_order),
#     OR_CI_upper = ifelse(OR_CI_upper <= 100, sprintf("%.2f", OR_CI_upper), sprintf("%.2e", OR_CI_upper))) %>%
#   arrange(desc(term)) %>%
#   kbl(caption = "1-shot Regimens - Odds Ratio and Confidence Intervals for composite outcome-associated Factors" , align = "c") %>%
#   kable_classic_2(full_width = F, html_font = "Cambria") %>%
#   save_kable("~/projects/vacunas_brands_2025/figures/OR/OR_vac_1shot_clinicalevent.jpg",
#              zoom = 10)

# Build the Forest plot
ggplot(coef_pval_df_hadm_2, 
       aes(x = OR, xmin = OR_CI_lower, xmax = OR_CI_upper, y = term)) +
  geom_point(size = 2, aes(color = adverse_protective)) +
  geom_errorbarh(height = 0.2, aes(color = adverse_protective)) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(x = "Odds Ratio", y = NULL, title = "Logistic Regression. Odds Ratio and Confidence Intervals \nfor Composite Outcome-associated Factors. \n1-shot Regimen") +
  theme_minimal() +
  scale_color_manual(
    values = c("#c0392b", "#27ae60", "gray70"),
    labels = c("Adverse", "Protective", "Inconclusive"),
    name = "Effect on Outcome") +
  scale_x_continuous(limits = c(0, 5)) +
  theme(
    plot.background = element_rect(fill = "white"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.title.position = "plot",
    legend.position = "top",
    axis.ticks = element_blank(),
    axis.text.x = element_text(color = "#2c3e50"),
    axis.text.y = element_text(color = "#2c3e50"
    ))

ggsave("~/projects/vacunas_brands_2025/figures/Forest_plot/fp_vac_1shot_clinicalevent.png", width = 8, height = 6, dpi = 300)

```

# Analysis of variable vac_2shot

## Logistic Regression of Clinical Event

### Fitting the model

```{r}
print('Logistic Regression of Clinical Event')
print(Sys.time())
logreg_hadm <- gam(
   clinical_event ~ s(age) + desc_sexo + variant_period + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc +  hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + ultima_inmun_infecc_bin + vac_2shot,
  data =  final_dataset,
  family=binomial(), 
  method = "REML")
print(Sys.time())
```

### Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_hadm_1 <- extract_coef_pval_OR(logreg_hadm)

```

### Forest Plot

```{r}
variable_order <- rev(c(
  "Intercept", "AstraZeneca+AstraZeneca", "AstraZeneca+Moderna", "AstraZeneca+Pfizer/BioNTech", "Janssen+Moderna", "Janssen+Pfizer/BioNTech", "Moderna+Moderna", "Moderna+Pfizer/BioNTech", "Pfizer/BioNTech+Moderna", "Pfizer/BioNTech+Pfizer/BioNTech",
 "No vaccination/infection", "Last vaccination/infection (>31-60 days ago)", "Last vaccination/infection (>61-90 days ago)", "Last vaccination/infection (>91-120 days ago)", "Last vaccination/infection (>121-180 days ago)", "Last vaccination/infection (>180 days ago)"))

coef_pval_df_hadm_2 <- coef_pval_df_hadm_1  %>%
  mutate(
    term = case_when(
      term == "(Intercept)" ~ "Intercept",
      term == "age" ~ "Age",
      term == "desc_sexoHombre" ~ "Sex (male)",
      term == "variant_periodα" ~ "Period of α predominance",
      term == "variant_periodα/Δ transition" ~ "α-Δ transition period",
      term == "variant_periodΔ" ~ "Period of Δ predominance",
      term == "variant_periodΔ/Ό transition" ~ "Δ-Ό transition period",
      term == "variant_periodΌ" ~ "Period of Ό predominance",
      term == "n_prev_infeccUno" ~ "Number of Previous Infections (1)",
      term == "n_prev_infeccDos" ~ "Number of Previous Infections (2)",
      term == "asmaSí" ~ "Asthma",
      term == "cardiopatia_isquemicaSí" ~ "Ischemic heart disease",
      term == "cirrosis_hepaticaSí" ~ "Hepatic cirrhosis",
      term == "diabetesSí" ~ "Diabetes",
      term == "epocSí" ~ "Chronic Obstructive Pulmonary Disease (COPD)",
      term == "hepatopatia_cronica_excepto_cirrosisSí" ~ "Chronic Hepatic Disease (except cirrhosis)",
      term == "hipertensionSí" ~ "Hypertension",
      term == "insuficiencia_cardiacaSí" ~ "Heart failure",
      term == "insuficiencia_renal_cronicaSí" ~ "Chronic kidney disease",
      term == "vihSí" ~ "HIV+",
      term == "cancer_hematologicoSí" ~ "Haematologic cancer",
      term == "cancer_organo_solidoSí" ~ "Solid organ cancer",
      term == "ultima_inmun_infecc_binNone" ~ "No vaccination/infection",
      term == "ultima_inmun_infecc_bin31-60" ~ "Last vaccination/infection (>31-60 days ago)",
      term == "ultima_inmun_infecc_bin31-60" ~ "Last vaccination/infection (>31-60 days ago)",
      term == "ultima_inmun_infecc_bin61-90" ~ "Last vaccination/infection (>61-90 days ago)",
      term == "ultima_inmun_infecc_bin91-120" ~ "Last vaccination/infection (>91-120 days ago)",
      term == "ultima_inmun_infecc_bin121-180" ~ "Last vaccination/infection (>121-180 days ago)",
      term == "ultima_inmun_infecc_bin>180" ~ "Last vaccination/infection (>180 days ago)",
      term == "vac_2shotAstraZeneca+AstraZeneca" ~ "AstraZeneca+AstraZeneca",
      term == "vac_2shotAstraZeneca+Moderna" ~ "AstraZeneca+Moderna",
      term == "vac_2shotAstraZeneca+Pfizer/BioNTech" ~ "AstraZeneca+Pfizer/BioNTech",
      term == "vac_2shotJanssen+Moderna" ~ "Janssen+Moderna",
      term == "vac_2shotJanssen+Pfizer/BioNTech" ~ "Janssen+Pfizer/BioNTech",
      term == "vac_2shotModerna+Moderna" ~ "Moderna+Moderna",
      term == "vac_2shotModerna+Pfizer/BioNTech" ~ "Moderna+Pfizer/BioNTech",
      term == "vac_2shotPfizer/BioNTech+Moderna" ~ "Pfizer/BioNTech+Moderna",
      term == "vac_2shotPfizer/BioNTech+Pfizer/BioNTech" ~ "Pfizer/BioNTech+Pfizer/BioNTech",
      term == "vac_2shotOther" ~ "Other",
      TRUE ~ term
    ),
    term = factor(term, levels = variable_order), 
    adverse_protective = case_when(
           OR_CI_lower > 1 & OR_CI_upper > 1 ~ "Adverse",
           OR_CI_lower < 1 & OR_CI_upper < 1 ~ "Protective",
           TRUE ~ "Inconclusive"
    ),
    adverse_protective = factor(adverse_protective, levels = c("Adverse", "Protective", "Inconclusive"))) %>%
  filter(term != "Intercept")

# Save OR table and print in console
write.csv(coef_pval_df_hadm_2,'~/projects/vacunas_brands_2025/data/oddsratio_vac_2shot_clinicalevent.csv')
htmlTable(coef_pval_df_hadm_2[,c("term","OR","OR_CI_lower","OR_CI_upper")], caption = "2-shot Regimen - Odds Ratio and Confidence Intervals for composite outcome-associated Factors")

# # Export OR table as kable 
# or_table <- coef_pval_df_hadm_2 %>%
#   select(term, OR, OR_CI_lower, OR_CI_upper) %>%
#   mutate(
#     term = factor(term, levels = variable_order),
#     OR_CI_upper = ifelse(OR_CI_upper <= 100, sprintf("%.2f", OR_CI_upper), sprintf("%.2e", OR_CI_upper))) %>%
#   arrange(desc(term)) %>%
#   kbl(caption = "2-shot Regimens - Odds Ratio and Confidence Intervals for composite outcome-associated Factors" , align = "c") %>%
#   kable_classic_2(full_width = F, html_font = "Cambria") %>%
#   save_kable("~/projects/vacunas_brands_2025/figures/OR/OR_vac_2shot_clinicalevent.jpg",
#              zoom = 10)

# Build the Forest plot
ggplot(coef_pval_df_hadm_2, 
       aes(x = OR, xmin = OR_CI_lower, xmax = OR_CI_upper, y = term)) +
  geom_point(size = 2, aes(color = adverse_protective)) +
  geom_errorbarh(height = 0.2, aes(color = adverse_protective)) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(x = "Odds Ratio", y = NULL, title = "Logistic Regression. Odds Ratio and Confidence Intervals \nfor Composite Outcome-associated Factors. \n2-shot Regimen") +
  theme_minimal() +
  scale_color_manual(
    values = c("#c0392b", "#27ae60", "gray70"),
    labels = c("Adverse", "Protective", "Inconclusive"),
    name = "Effect on Outcome") +
  scale_x_continuous(limits = c(0, 5)) +
  theme(
    plot.background = element_rect(fill = "white"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.title.position = "plot",
    legend.position = "top",
    axis.ticks = element_blank(),
    axis.text.x = element_text(color = "#2c3e50"),
    axis.text.y = element_text(color = "#2c3e50"
    ))

ggsave("~/projects/vacunas_brands_2025/figures/Forest_plot/fp_vac_2shot_clinicalevent.png", width = 8, height = 6, dpi = 300)

```

# Analysis of variable vac_3shot

## Logistic Regression of Clinical Event

### Fitting the model

```{r}
print('Logistic Regression of Clinical Event')
print(Sys.time())
logreg_hadm <- gam(
   clinical_event ~ s(age) + desc_sexo + variant_period + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc +  hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + ultima_inmun_infecc_bin + vac_3shot,
  data =  final_dataset,
  family=binomial(), 
  method = "REML")
print(Sys.time())
```

### Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_hadm_1 <- extract_coef_pval_OR(logreg_hadm)

```

### Forest Plot

```{r}
variable_order <- rev(c(
  "Intercept", "AstraZeneca+AstraZeneca+Moderna", "AstraZeneca+AstraZeneca+Pfizer/BioNTech", "AstraZeneca+Pfizer/BioNTech+Moderna", 
"AstraZeneca+Pfizer/BioNTech+Pfizer/BioNTech", "Moderna+Moderna+Moderna", "Moderna+Moderna+Pfizer/BioNTech", "Moderna+Pfizer/BioNTech+Pfizer/BioNTech", "Pfizer/BioNTech+Pfizer/BioNTech+Moderna", "Pfizer/BioNTech+Pfizer/BioNTech+Pfizer/BioNTech", 
 "No vaccination/infection", "Last vaccination/infection (>31-60 days ago)", "Last vaccination/infection (>61-90 days ago)", "Last vaccination/infection (>91-120 days ago)", "Last vaccination/infection (>121-180 days ago)", "Last vaccination/infection (>180 days ago)"))

coef_pval_df_hadm_2 <- coef_pval_df_hadm_1  %>%
  mutate(
    term = case_when(
      term == "(Intercept)" ~ "Intercept",
      term == "age" ~ "Age",
      term == "desc_sexoHombre" ~ "Sex (male)",
      term == "variant_periodα" ~ "Period of α predominance",
      term == "variant_periodα/Δ transition" ~ "α-Δ transition period",
      term == "variant_periodΔ" ~ "Period of Δ predominance",
      term == "variant_periodΔ/Ό transition" ~ "Δ-Ό transition period",
      term == "variant_periodΌ" ~ "Period of Ό predominance",
      term == "n_prev_infeccUno" ~ "Number of Previous Infections (1)",
      term == "n_prev_infeccDos" ~ "Number of Previous Infections (2)",
      term == "asmaSí" ~ "Asthma",
      term == "cardiopatia_isquemicaSí" ~ "Ischemic heart disease",
      term == "cirrosis_hepaticaSí" ~ "Hepatic cirrhosis",
      term == "diabetesSí" ~ "Diabetes",
      term == "epocSí" ~ "Chronic Obstructive Pulmonary Disease (COPD)",
      term == "hepatopatia_cronica_excepto_cirrosisSí" ~ "Chronic Hepatic Disease (except cirrhosis)",
      term == "hipertensionSí" ~ "Hypertension",
      term == "insuficiencia_cardiacaSí" ~ "Heart failure",
      term == "insuficiencia_renal_cronicaSí" ~ "Chronic kidney disease",
      term == "vihSí" ~ "HIV+",
      term == "cancer_hematologicoSí" ~ "Haematologic cancer",
      term == "cancer_organo_solidoSí" ~ "Solid organ cancer",
      term == "ultima_inmun_infecc_binNone" ~ "No vaccination/infection",
      term == "ultima_inmun_infecc_bin31-60" ~ "Last vaccination/infection (>31-60 days ago)",
      term == "ultima_inmun_infecc_bin31-60" ~ "Last vaccination/infection (>31-60 days ago)",
      term == "ultima_inmun_infecc_bin61-90" ~ "Last vaccination/infection (>61-90 days ago)",
      term == "ultima_inmun_infecc_bin91-120" ~ "Last vaccination/infection (>91-120 days ago)",
      term == "ultima_inmun_infecc_bin121-180" ~ "Last vaccination/infection (>121-180 days ago)",
      term == "ultima_inmun_infecc_bin>180" ~ "Last vaccination/infection (>180 days ago)",
      term == "vac_3shotAstraZeneca+AstraZeneca+Moderna" ~ "AstraZeneca+AstraZeneca+Moderna",
      term == "vac_3shotAstraZeneca+AstraZeneca+Pfizer/BioNTech" ~ "AstraZeneca+AstraZeneca+Pfizer/BioNTech",
      term == "vac_3shotAstraZeneca+Pfizer/BioNTech+Moderna" ~ "AstraZeneca+Pfizer/BioNTech+Moderna",
      term == "vac_3shotAstraZeneca+Pfizer/BioNTech+Pfizer/BioNTech" ~ "AstraZeneca+Pfizer/BioNTech+Pfizer/BioNTech",
      term == "vac_3shotModerna+Moderna+Moderna" ~ "Moderna+Moderna+Moderna",
      term == "vac_3shotModerna+Moderna+Pfizer/BioNTech" ~ "Moderna+Moderna+Pfizer/BioNTech",
      term == "vac_3shotModerna+Pfizer/BioNTech+Pfizer/BioNTech" ~ "Moderna+Pfizer/BioNTech+Pfizer/BioNTech",
      term == "vac_3shotPfizer/BioNTech+Pfizer/BioNTech+Moderna" ~ "Pfizer/BioNTech+Pfizer/BioNTech+Moderna",
      term == "vac_3shotPfizer/BioNTech+Pfizer/BioNTech+Pfizer/BioNTech" ~ "Pfizer/BioNTech+Pfizer/BioNTech+Pfizer/BioNTech",
      TRUE ~ term
    ),
    term = factor(term, levels = variable_order), 
    adverse_protective = case_when(
           OR_CI_lower > 1 & OR_CI_upper > 1 ~ "Adverse",
           OR_CI_lower < 1 & OR_CI_upper < 1 ~ "Protective",
           TRUE ~ "Inconclusive"
    ),
    adverse_protective = factor(adverse_protective, levels = c("Adverse", "Protective", "Inconclusive"))) %>%
  filter(term != "Intercept")

# Save OR table and print in console
write.csv(coef_pval_df_hadm_2,'~/projects/vacunas_brands_2025/data/oddsratio_vac_3shot_clinicalevent.csv')
htmlTable(coef_pval_df_hadm_2[,c("term","OR","OR_CI_lower","OR_CI_upper")], caption = "3-shot Regimen - Odds Ratio and Confidence Intervals for composite outcome-associated Factors")

# # Export OR table as kable 
# or_table <- coef_pval_df_hadm_2 %>%
#   select(term, OR, OR_CI_lower, OR_CI_upper) %>%
#   mutate(
#     term = factor(term, levels = variable_order),
#     OR_CI_upper = ifelse(OR_CI_upper <= 100, sprintf("%.2f", OR_CI_upper), sprintf("%.2e", OR_CI_upper))) %>%
#   arrange(desc(term)) %>%
#   kbl(caption = "3-shot Regimens - Odds Ratio and Confidence Intervals for composite outcome-associated Factors" , align = "c") %>%
#   kable_classic_2(full_width = F, html_font = "Cambria") %>%
#   save_kable("~/projects/vacunas_brands_2025/figures/OR/OR_vac_3shot_clinicalevent.jpg",
#              zoom = 10)

# Build the Forest plot
ggplot(coef_pval_df_hadm_2, 
       aes(x = OR, xmin = OR_CI_lower, xmax = OR_CI_upper, y = term)) +
  geom_point(size = 2, aes(color = adverse_protective)) +
  geom_errorbarh(height = 0.2, aes(color = adverse_protective)) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(x = "Odds Ratio", y = NULL, title = "Logistic Regression. Odds Ratio and Confidence Intervals \nfor Composite Outcome-associated Factors. \n3-shot Regimen") +
  theme_minimal() +
  scale_color_manual(
    values = c("#c0392b", "#27ae60", "gray70"),
    labels = c("Adverse", "Protective", "Inconclusive"),
    name = "Effect on Outcome") +
  scale_x_continuous(limits = c(0, 5)) +
  theme(
    plot.background = element_rect(fill = "white"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.title.position = "plot",
    legend.position = "top",
    axis.ticks = element_blank(),
    axis.text.x = element_text(color = "#2c3e50"),
    axis.text.y = element_text(color = "#2c3e50"
    ))

ggsave("~/projects/vacunas_brands_2025/figures/Forest_plot/fp_vac_3shot_clinicalevent.png", width = 8, height = 6, dpi = 300)

```
